"""
scripts/seed_incidents.py — Seed incidents + test ground truth from manifest.

Phase 1 deliverable (canonicalization-enrichment plan, drift fix #1, #2).

Reads a test-data manifest JSON (generated by the test-data-generation script
next to the enriched CSV) and populates two DB tables:

  - incidents(incident_id, description, expected_vernacular, ...)
      * One row per incident in manifest['incidents']
      * expected_vernacular is a JSON array of terms mined from the
        description + concept_id; `expected_canonical_cluster` stays NULL
        until Phase 5 back-fills it.

  - test_concept_ground_truth(ticket_id, concept_id, source='manifest')
      * One row per (ticket, concept) pair in manifest['cluster_ground_truth']
      * Used by Phase 3/5/9 regression tests as the truth side of
        precision/recall.

Idempotent: INSERT OR REPLACE for incidents (lets you re-run after
description tweaks), INSERT OR IGNORE for ground truth.

Usage:
    python scripts/seed_incidents.py
    python scripts/seed_incidents.py --manifest path/to/manifest.json
    python scripts/seed_incidents.py --db data/local_warehouse.db
    python scripts/seed_incidents.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

# Project root import bootstrap
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

from src.data.connection_factory import atomic, get_connection   # noqa: E402

logger = logging.getLogger("alma.seed_incidents")
logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

import os
DEFAULT_MANIFEST = Path(os.environ.get(
    "ALMA_TEST_MANIFEST",
    str(Path(__file__).resolve().parent.parent
        / "data" / "test_fixtures" / "alma_test_10000_1_manifest.json"),
))
DEFAULT_DB = Path(__file__).resolve().parent.parent / "data" / "local_warehouse.db"


# ───────────────────────────────────────────────────────────────────────────
# vernacular synthesis
# ───────────────────────────────────────────────────────────────────────────

_STOPWORDS = {
    "the", "a", "an", "of", "on", "with", "for", "and", "or", "but",
    "is", "was", "were", "be", "been", "being",
    "in", "at", "to", "by", "from", "as",
}


def _synthesize_vernacular(description: str, concept_id: str) -> list[str]:
    """Mine expected terms from the incident description + concept_id.

    Phase 5 will replace this with LLM-derived vernacular rooted in actual
    ticket body content, but at Phase 1 we only need a seed list that lets
    Phase 9's tag-audit test distinguish signal from noise.

    Strategy: tokenize description + concept_id, drop stopwords, lowercase,
    dedupe. Also split the concept_id on underscores to surface terms like
    'portal', 'access', 'fail' individually.
    """
    tokens: list[str] = []
    for source in (description, concept_id.replace("_", " ")):
        for raw in re.findall(r"[A-Za-z0-9]+", source):
            w = raw.lower()
            if len(w) < 3 or w in _STOPWORDS:
                continue
            tokens.append(w)
    # preserve insertion order, dedupe
    seen: set[str] = set()
    out: list[str] = []
    for t in tokens:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


# ───────────────────────────────────────────────────────────────────────────
# core seeding
# ───────────────────────────────────────────────────────────────────────────

def seed_incidents(conn, manifest: dict) -> int:
    """Upsert incidents rows from manifest['incidents']. Returns rows written."""
    incidents = manifest.get("incidents") or {}
    if not isinstance(incidents, dict):
        logger.warning("Manifest has no 'incidents' dict; skipping incidents seed")
        return 0

    written = 0
    for incident_id, info in incidents.items():
        if not isinstance(info, dict):
            continue
        description = info.get("description", "")
        concept_id = info.get("expected_concept", "")
        vernacular = _synthesize_vernacular(description, concept_id)

        # Extract date from tail of incident_id if it looks like _MMDD
        m = re.search(r"_(\d{4})$", incident_id)
        incident_date = None
        if m:
            mmdd = m.group(1)
            # Best effort — assume current year (2026 per test data generation)
            incident_date = f"2026-{mmdd[:2]}-{mmdd[2:]}"

        notes_obj = {
            "source": "manifest",
            "tagged_tickets": info.get("tagged_tickets"),
            "correct_tags": info.get("correct_tags"),
            "mis_tags": info.get("mis_tags"),
            "expected_concept": concept_id,
        }

        conn.execute(
            """
            INSERT INTO incidents
                (incident_id, description, incident_date,
                 expected_vernacular, expected_canonical_cluster, notes)
            VALUES (?, ?, ?, ?, NULL, ?)
            ON CONFLICT(incident_id) DO UPDATE SET
                description         = excluded.description,
                incident_date       = excluded.incident_date,
                expected_vernacular = excluded.expected_vernacular,
                notes               = excluded.notes
            """,
            (
                incident_id,
                description,
                incident_date,
                json.dumps(vernacular),
                json.dumps(notes_obj),
            ),
        )
        written += 1

    logger.info("Seeded %d incident(s)", written)
    return written


def seed_ground_truth(conn, manifest: dict) -> int:
    """Load manifest['cluster_ground_truth'] into test_concept_ground_truth."""
    gt = manifest.get("cluster_ground_truth") or {}
    if not isinstance(gt, dict):
        logger.warning("Manifest has no 'cluster_ground_truth' dict; skipping")
        return 0

    written = 0
    for concept_id, ticket_ids in gt.items():
        if not isinstance(ticket_ids, list):
            continue
        for tid in ticket_ids:
            if tid is None:
                continue
            conn.execute(
                """
                INSERT OR IGNORE INTO test_concept_ground_truth
                    (ticket_id, concept_id, source)
                VALUES (?, ?, 'manifest')
                """,
                (str(tid), concept_id),
            )
            written += 1

    logger.info("Wrote %d ground-truth (ticket, concept) row(s)", written)
    return written


def load_manifest(path: Path) -> dict:
    """Read and JSON-parse the manifest at `path`. Raises on missing / malformed."""
    if not path.exists():
        raise FileNotFoundError(f"manifest not found: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"manifest is not valid JSON: {exc}") from exc


# ───────────────────────────────────────────────────────────────────────────
# CLI
# ───────────────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1].strip())
    p.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST,
                   help="Path to test-data manifest JSON")
    p.add_argument("--db", type=Path, default=DEFAULT_DB,
                   help="Path to SQLite database")
    p.add_argument("--dry-run", action="store_true",
                   help="Parse manifest and print summary without writing")
    args = p.parse_args(argv)

    manifest = load_manifest(args.manifest)
    logger.info("Loaded manifest: %d tickets, %d concepts, %d incidents",
                manifest.get("total_tickets", 0),
                len(manifest.get("cluster_ground_truth") or {}),
                len(manifest.get("incidents") or {}))

    if args.dry_run:
        logger.info("Dry run — no DB writes")
        return 0

    conn = get_connection(args.db, for_writer=True)
    try:
        with atomic(conn):
            incidents_written = seed_incidents(conn, manifest)
            gt_written = seed_ground_truth(conn, manifest)
    finally:
        conn.close()

    logger.info("Done. incidents=%d, ground_truth_rows=%d",
                incidents_written, gt_written)
    return 0


if __name__ == "__main__":
    sys.exit(main())
